[programs.localnet]
exam = "6U9komsBuAarVoHz8am73W9Aa6QR9Cvh8sqDLFkCrY7t"

[programs.devnet]
exam = "6U9komsBuAarVoHz8am73W9Aa6QR9Cvh8sqDLFkCrY7t"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/ildar/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
